"""Structured deliberation artifacts — 7 artifact types per MetaGPT+Urban Planning SOP.

All agents output these structured artifacts, NOT free-form chat messages.
This ensures downstream agents can consistently read, compare, score, and persist outputs.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class Stance(str, Enum):
    SUPPORT = "support"
    CONDITIONAL_SUPPORT = "conditional_support"
    NEUTRAL = "neutral"
    CONDITIONAL_OPPOSE = "conditional_oppose"
    OPPOSE = "oppose"


class ArtifactStatus(str, Enum):
    DRAFT = "draft"
    UNDER_REVIEW = "under_review"
    APPROVED = "approved"
    REJECTED = "rejected"


class MotionType(str, Enum):
    """The small, deliberation-oriented subset of Robert's Rules we support."""
    MAIN = "main_motion"
    AMENDMENT = "amendment"
    PROCEDURAL = "procedural"
    INFORMATION = "information_request"


class MotionStatus(str, Enum):
    DRAFT = "draft"
    AWAITING_SECOND = "awaiting_second"
    DEBATE_OPEN = "debate_open"
    AMENDMENT_PENDING = "amendment_pending"
    VOTING = "voting"
    ADOPTED = "adopted"
    REJECTED = "rejected"
    WITHDRAWN = "withdrawn"


class RoleType(str, Enum):
    RESIDENT = "resident"
    VULNERABLE_GROUP = "vulnerable_group"
    EXPERT = "expert"
    MANAGER = "manager"
    BUSINESS = "business"
    MODERATOR = "moderator"


# ── 1. Issue Definition Card ─────────────────────────────────────────────────

@dataclass
class IssueDefinitionCard:
    """议题定义卡 — generated by topic analysis, consumed by all agents."""
    topic: str = ""
    question: str = ""
    scope: str = ""
    goals: list[str] = field(default_factory=list)
    constraints_summary: list[str] = field(default_factory=list)
    unknown_items: list[str] = field(default_factory=list)
    # SOP v1.2 tracking fields
    artifact_id: str = ""
    stage_id: str = ""


# ── 2. Evidence Ledger (already exists as EvidenceCard in evidence.py) ──────
# Re-export for convenience
# ── 3. Stakeholder Map ──────────────────────────────────────────────────────

@dataclass
class StakeholderMap:
    """利益相关者地图 — maps all affected groups and their relationships."""
    groups: list[dict] = field(default_factory=list)
    relationships: list[dict] = field(default_factory=list)
    power_asymmetry: str = ""
    silent_stakeholders: list[str] = field(default_factory=list)
    artifact_id: str = ""
    stage_id: str = ""


# ── 4. Position Card ────────────────────────────────────────────────────────

@dataclass
class PositionCard:
    """立场陈述卡 — each agent's structured stance output.

    JSON Schema (from doc Table 0, row 4):
    {
      "agent_id": "resident_parent_01",
      "stakeholder_group": "育儿家庭",
      "stance": "conditional_support",
      "claims": ["具体主张1", "具体主张2"],
      "evidence_ids": ["E-03", "E-12"],
      "non_negotiables": ["不可退让的底线"],
      "risks": ["风险1"],
      "suggested_changes": ["对方案的修改建议"],
      "confidence": 0.72
    }
    """
    agent_id: str = ""
    stakeholder_group: str = ""
    stance: Stance = Stance.NEUTRAL
    claims: list[str] = field(default_factory=list)
    evidence_ids: list[str] = field(default_factory=list)
    non_negotiables: list[str] = field(default_factory=list)
    risks: list[str] = field(default_factory=list)
    suggested_changes: list[str] = field(default_factory=list)
    confidence: float = 0.5
    round_no: int = 1
    # SOP v1.2 tracking
    artifact_id: str = ""
    stage_id: str = ""
    produced_by: str = ""
    input_refs: list[str] = field(default_factory=list)
    evidence_refs: list[str] = field(default_factory=list)
    validation_status: str = "pending"


# ── 5. Round Summary ────────────────────────────────────────────────────────

@dataclass
class RoundSummary:
    """轮次摘要 — moderator output after each fishbowl round.

    MUST preserve minority views — NOT just majority consensus.
    6 required fields per the document specification.
    """
    round_no: int = 0
    inner_circle: list[str] = field(default_factory=list)
    majority_views: list[str] = field(default_factory=list)
    minority_views: list[str] = field(default_factory=list)
    unresolved_conflicts: list[str] = field(default_factory=list)
    evidence_gaps: list[str] = field(default_factory=list)
    next_round_questions: list[str] = field(default_factory=list)
    involved_groups: list[str] = field(default_factory=list)
    # SOP v1.2 tracking
    artifact_id: str = ""
    stage_id: str = ""
    produced_by: str = ""
    round_id: int = -1
    validation_status: str = "pending"


# ── 6. Conflict Matrix ──────────────────────────────────────────────────────

@dataclass
class ConflictAxis:
    """A single axis of conflict between stakeholder groups."""
    name: str = ""
    parties: list[str] = field(default_factory=list)
    intensity: str = "medium"  # low / medium / high
    description: str = ""
    resolution_status: str = "open"


@dataclass
class ConflictMatrix:
    """冲突矩阵 — maps all axes of conflict between stakeholders.

    From doc Table 0, row 5: generated by conflict/opposition agent,
    consumed by proposal agent.
    """
    axes: list[ConflictAxis] = field(default_factory=list)
    hidden_conflicts: list[str] = field(default_factory=list)
    pseudo_consensus_flags: list[str] = field(default_factory=list)
    artifact_id: str = ""
    stage_id: str = ""
    produced_by: str = ""


# ── 7. Proposal Card ────────────────────────────────────────────────────────

@dataclass
class ProposalCard:
    """方案卡 — structured proposal with version tracking.

    From doc Table 0, row 6: generated by proposal agent,
    consumed by evaluation agents.
    """
    proposal_id: str = ""
    version: int = 1
    title: str = ""
    content: str = ""
    status: ArtifactStatus = ArtifactStatus.DRAFT
    claims: list[str] = field(default_factory=list)
    responsible: str = ""
    timeline: str = ""
    resources: str = ""
    risks: str = ""
    evaluation_criteria: list[str] = field(default_factory=list)
    evidence_ids: list[str] = field(default_factory=list)
    revision_count: int = 0
    artifact_id: str = ""
    stage_id: str = ""
    produced_by: str = ""
    input_refs: list[str] = field(default_factory=list)
    evidence_refs: list[str] = field(default_factory=list)
    validation_status: str = "pending"


# ── 8. Validation Result ────────────────────────────────────────────────────

@dataclass
class ValidationResult:
    """验证结果 — from 6 validators checking the proposal."""
    passed: bool = False
    hard_constraint_errors: list[str] = field(default_factory=list)
    evidence_errors: list[str] = field(default_factory=list)
    fairness_risks: list[str] = field(default_factory=list)
    conflict_errors: list[str] = field(default_factory=list)
    feasibility_errors: list[str] = field(default_factory=list)
    consistency_errors: list[str] = field(default_factory=list)
    revision_instructions: list[str] = field(default_factory=list)
    artifact_id: str = ""
    stage_id: str = ""


# ── 9. Agent Contract (SOP v1.2 S3) ──────────────────────────────────────────

@dataclass
class AgentContract:
    """Agent 职责合约 — defines what each agent is responsible for, its inputs,
    outputs, validation rules, and boundaries. Generated at S3 (Role Mapping).

    Per SOP v1.2 §2.1: each agent must have an explicit contract so it knows
    exactly what it should and should not do during deliberation.
    """
    contract_id: str = ""
    agent_id: str = ""
    agent_name: str = ""
    role: str = ""  # archetype / role name
    responsibility: str = ""  # what this agent must deliver
    input_artifacts: list[str] = field(default_factory=list)  # artifact types expected
    output_artifacts: list[str] = field(default_factory=list)  # artifact types to produce
    validation_rules: list[str] = field(default_factory=list)  # rules outputs must satisfy
    boundary_rules: list[str] = field(default_factory=list)  # what agent CANNOT do/say
    artifact_id: str = ""
    stage_id: str = ""
    produced_by: str = ""


# ── 10. Deliberation Plan (SOP v1.2 S5) ──────────────────────────────────────

@dataclass
class DeliberationPlan:
    """议事行动计划 — each inner-circle agent generates this before speaking.

    Per SOP v1.2 §8 (S5): ensures agents enter the round knowing their goal,
    non-negotiables, concessions, questions to others, and evidence to use.
    """
    plan_id: str = ""
    agent_id: str = ""
    agent_name: str = ""
    round_id: int = -1
    round_goal: str = ""  # what to achieve in this round
    core_interest: str = ""  # single most important interest
    non_negotiables: list[str] = field(default_factory=list)  # red lines
    possible_concessions: list[str] = field(default_factory=list)  # areas of flexibility
    question_to_others: str = ""  # question for other agents
    evidence_to_use: list[str] = field(default_factory=list)  # evidence IDs
    artifact_id: str = ""
    stage_id: str = "S5"
    produced_by: str = ""
    input_refs: list[str] = field(default_factory=list)
    validation_status: str = "pending"


# ── 11. Outer Observation Card (SOP v1.2 S7) ─────────────────────────────────

@dataclass
class OuterObservationCard:
    """外圈观察卡 — outer-circle agents submit this after inner-circle speeches.

    Per SOP v1.2 §4.6: outer agents don't speak but must record what was missed,
    objections, missing evidence, and whether they want to enter inner circle.
    """
    card_id: str = ""
    observer_id: str = ""
    observer_name: str = ""
    round_id: int = -1
    missed_issue: str = ""  # what inner circle failed to address
    objection: str = ""  # disagreement with inner circle positions
    evidence_needed: list[str] = field(default_factory=list)  # missing evidence types
    request_to_enter_inner_circle: bool = False
    reason_to_enter: str = ""
    artifact_id: str = ""
    stage_id: str = "S7"
    produced_by: str = ""
    validation_status: str = "pending"


# ── 12. Review Card (SOP v1.2 S10) ───────────────────────────────────────────

@dataclass
class ReviewCard:
    """方案审查卡 — evaluates proposal against hard constraints, public resources,
    and universalization test.

    Per SOP v1.2 §8 (S10): produced by Rule Checker + Urban Evaluator +
    Universalization Agent before voting.
    """
    review_id: str = ""
    proposal_id: str = ""
    hard_constraint_passed: bool = False
    public_resource_score: dict[str, int] = field(default_factory=dict)
    universalization_result: str = ""  # pass | fail
    universalization_rationale: str = ""
    required_revisions: list[str] = field(default_factory=list)
    recommendation: str = ""  # accept | revise | reject
    artifact_id: str = ""
    stage_id: str = "S10"
    produced_by: str = ""
    reviewer: str = ""


# ── 13. Observer Snapshot (SOP v1.2 S8) ──────────────────────────────────────

@dataclass
class ObserverSnapshot:
    """观察员快照 — per-round metrics quantifying deliberation quality.

    Per SOP v1.2 §11: produced after each round's summary. Tracks speaker
    fairness, evidence grounding, minority retention, and boundary violations.
    """
    snapshot_id: str = ""
    round_id: int = -1
    speaker_share: dict[str, float] = field(default_factory=dict)
    grounding_rate: float = 0.0
    minority_retention: float = 0.0
    role_boundary_violations: int = 0
    unanswered_questions: list[str] = field(default_factory=list)
    anomaly_flags: list[str] = field(default_factory=list)
    artifact_id: str = ""
    stage_id: str = "S8"
    produced_by: str = ""


# ── 14. Gate Check Result ────────────────────────────────────────────────────

@dataclass
class GateCheckResult:
    """校验门检查结果 — output from a single validation gate.

    Per SOP v1.2 §10: each gate check returns status (pass/revise/reject),
    issues found, and required actions before proceeding.
    """
    gate_name: str = ""
    stage_id: str = ""
    status: str = "pass"  # pass | revise | reject
    issues: list[str] = field(default_factory=list)
    required_action: list[str] = field(default_factory=list)
    artifact_id: str = ""
    produced_by: str = ""


# ── 15. Procedural artifacts (Robert's Rules adapted for deliberation) ─────

@dataclass
class Motion:
    """A traceable matter placed before the deliberation.

    A second means the matter deserves discussion, not that the seconder
    supports it.  The runtime, rather than an LLM, controls status changes.
    """
    motion_id: str = ""
    motion_type: MotionType = MotionType.MAIN
    proposer_id: str = ""
    proposer_name: str = ""
    content: str = ""
    status: MotionStatus = MotionStatus.DRAFT
    parent_motion_id: str | None = None
    seconded_by: str | None = None
    seconded_by_name: str | None = None
    rationale: str = ""
    round_id: int = 0
    votes: dict[str, str] = field(default_factory=dict)
    adopted_amendments: list[str] = field(default_factory=list)


@dataclass
class ProceduralEvent:
    """Append-only audit record for a procedural decision."""
    event_id: str = ""
    action: str = ""
    actor_id: str = ""
    actor_name: str = ""
    target_id: str = ""
    result: str = "accepted"  # accepted | rejected | noted
    reason: str = ""
    stage_id: str = ""
    round_id: int = 0


@dataclass
class CommitmentCard:
    """Separates textual agreement from willingness to execute a proposal."""
    agent_id: str = ""
    agent_name: str = ""
    proposal_id: str = ""
    acceptance: str = "conditional"  # support | conditional | oppose
    conditions: list[str] = field(default_factory=list)
    willing_to_execute: bool = False
    execution_risk: str = ""
